title: Alex GistHub Blog
author: Gerardo González
email: gerardo_igonzalez@comunidad.unam.mx
description: > # this means to ignore newlines until "baseurl:"
Esta página contiene los codigos y conceptos necesarios para el desarrollo de nuevos proyectos en python tabjados por Gerardo González

# social links
twitter_username: @lex_i1003 # DO NOT include the @ character, or else the build will fail!
github_username:  Alex1003i # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
